In [1]:
import pandas as pd
import numpy as np

In [27]:
data = pd.read_csv(r'C:\Users\apaks\Desktop\Real Estate Project\artifacts\data\raw-data\appartments.csv')

In [28]:
data.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."

In [29]:
data.columns

Index(['PropertyName', 'PropertySubName', 'NearbyLocations',
       'LocationAdvantages', 'Link', 'PriceDetails', 'TopFacilities'],
      dtype='object')

### Propert Name

In [30]:
data['PropertyName'].nunique()

247

property name contains the names of the different real estate societies in Gurgaon

### PropertySubname

In [31]:
data['PropertySubName']

0           2, 3, 4 BHK Apartment in Sector 113, Gurgaon
1              3, 4 BHK Apartment in Sector 111, Gurgaon
2      Land, 3, 4 BHK Independent Floor in Sector 63,...
3           2, 3, 4 BHK Apartment in Sector 108, Gurgaon
4        2, 3 BHK Independent Floor in Sector 93 Gurgaon
                             ...
242        2, 3, 4 BHK Apartment in DLF Phase 5, Gurgaon
243             1, 2 BHK Apartment in Sector 86, Gurgaon
244      2, 3, 4, 5 BHK Apartment in Sector 103, Gurgaon
245            2, 3 BHK Apartment in Sector 37D, Gurgaon
246             2, 3 BHK Apartment in Sector 84, Gurgaon
Name: PropertySubName, Length: 247, dtype: object

PropertSubName contains the types of appartment the society offers and the sector info

### NearbyLocations

In [32]:
data['NearbyLocations']

0      ['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...
1      ['DPSG Palam Vihar Gurugram', 'The NorthCap Un...
2      ['AIPL Business Club Sector 62', 'Heritage Xpe...
3      ['The Shikshiyan School', 'WTC Plaza', 'Luxus ...
4      ['Pranavananda Int. School', 'DLF Site central...
                             ...
242    ['Sector 42-43 Metro Station', 'Paras Hospital...
243    ['Aarvy Healthcare Super Speciality', "St. Xav...
244    ['Dwarka Expressway', 'S N International Schoo...
245    ['Suncity School', 'Gurugram Road', 'Dwarka Ex...
246    ['Sector 84 Road', 'Delhi Public School, Secto...
Name: NearbyLocations, Length: 247, dtype: object

NearbyLocations contains a list of some nearby locations

In [33]:
data['LocationAdvantages'].iloc[0]

"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"

In [34]:
data['NearbyLocations'].iloc[0]

"['Bajghera Road', 'Palam Vihar Halt', 'DPSG Palam Vihar', 'Park Hospital', 'Gurgaon Railway Station']"

-   LocationAdvantages contains dictionary with the name of the nearby location and the distance from the society. 
-   NearbyLocations is a subset of locations mentioned in LocationAdvantages
-   NearbyLocations can be dropped later

### Link

In [35]:
data['Link']

0      https://www.99acres.com/smartworld-one-dxp-sec...
1      https://www.99acres.com/m3m-crown-sector-111-g...
2      https://www.99acres.com/adani-brahma-samsara-v...
3      https://www.99acres.com/sobha-city-sector-108-...
4      https://www.99acres.com/signature-global-city-...
                             ...
242    https://www.99acres.com/dlf-princeton-estate-d...
243    https://www.99acres.com/pyramid-urban-homes-2-...
244    https://www.99acres.com/satya-the-hermitage-se...
245    https://www.99acres.com/bptp-spacio-sector-37d...
246    https://www.99acres.com/ss-the-coralwood-secto...
Name: Link, Length: 247, dtype: object

contains links to the website. links seem to be non functional - can be dropped later

### PriceDetails

In [37]:
data['PriceDetails'].iloc[0]

"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}"

Contains nested dict with room type and its details

### TopFacilities

In [39]:
data['TopFacilities'].iloc[0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

TopFacilities containsfacilities offered in the society. Can be used to segment socities based on luxury

## Recommender System - based on TopFacilities

In [40]:
df = data.copy()

In [ ]:
df.drop(columns = ['NearbyLocations', 'Link'], inplace = True)      # drop unnecessary columns

In [41]:
df[['PropertyName', 'TopFacilities']]

,PropertyName,TopFacilities
0,Smartworld One DXP,"['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."
...,...,...
242,DLF Princeton Estate,"['Swimming Pool', 'Medical Centre', 'Laundry',..."
243,Pyramid Urban Homes 2,"['Shopping Centre', 'Community Hall', '24x7 Se..."
244,Satya The Hermitage,"['Bus Shelter', 'Swimming Pool', 'Business Lou..."
245,BPTP Spacio,"['Swimming Pool', 'Card Room', 'Piped Gas', 'P..."
246,SS The Coralwood,"['Swimming Pool', 'School', 'Solar Lighting', ..."

In [54]:
df['TopFacilities'].iloc[0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

In [65]:
import re
def extract_facilities(row):
    return re.findall("'(.*?)'", row)       # extract everything inside single inverted comas and return list

df['TopFacilities'] = df['TopFacilities'].apply(extract_facilities)

In [66]:
df.head()

,PropertyName,PropertySubName,LocationAdvantages,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...","{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...","{'3 BHK': {'building_type': 'Apartment', 'area...","[Bowling Alley, Mini Theatre, Manicured Garden..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",{'3 BHK': {'building_type': 'Independent Floor...,"[Terrace Garden, Gazebo, Fountain, Amphitheatr..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...","{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Volley Ball Court, Aerobics Ce..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","{'Pranavananda Int. School': '450 m', 'DLF Sit...",{'2 BHK': {'building_type': 'Independent Floor...,"[Mini Theatre, Doctor on Call, Concierge Servi..."

In [68]:
# convert the list into strings

df['TopFacilities'] = df['TopFacilities'].apply(' '.join)

In [70]:
df['TopFacilities'].iloc[0]

'Swimming Pool Salon Restaurant Spa Cafeteria Sun Deck 24x7 Security Club House Gated Community'

applying tfidf vectoriser to TopFacilities column

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english', ngram_range=(1,2))
tfidf_matrix = tfidf.fit_transform(df['TopFacilities'])

In [74]:
tfidf_matrix.toarray()

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.1438338,
        0.1438338],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]], shape=(247, 953))

In [108]:
# cosine similarity of each vector with allthe other vectors 

from sklearn.metrics.pairwise import cosine_similarity

cos_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [144]:
def recommend_properties(property_name, cosine_sim = cos_sim1):
    # get the index of the property name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]
    
    # similarity score of the idx item with respect to other items. Using enumerate to also pull the position of the elements
    sim_scores = list(enumerate(cos_sim1[idx]))
    
    

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse= True)       # sorting in descending order based on similarity score which is at index 1 in each tuple inside the big list 
    print(sim_scores)
    del sim_scores[0]       # remove the 0th index as it is the similarity score with itself
    print(sim_scores)
    
    # extract top 5 simarity scores and their indicies
    sim_scores = sim_scores[:5]

    # extract the indicies from the list of tupples sim_scores
    sim_property_indicies = [i[0] for i in sim_scores]

    recomendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[sim_property_indicies],
        'SimilarityScore': sim_property_indicies
    })

    return recomendations_df

In [145]:
print(recommend_properties("DLF The Arbour"))

[(11, np.float64(0.9999999999999999)), (64, np.float64(0.45311114162955807)), (217, np.float64(0.4200539456275653)), (93, np.float64(0.416805651127417)), (154, np.float64(0.39911681617817335)), (0, np.float64(0.38896543251188437)), (73, np.float64(0.38838855199503136)), (63, np.float64(0.3768794014077303)), (18, np.float64(0.3575160490039907)), (186, np.float64(0.35342137210419367)), (243, np.float64(0.348593386634705)), (14, np.float64(0.3452581845696204)), (135, np.float64(0.3277061555077906)), (65, np.float64(0.3251042839624321)), (37, np.float64(0.3203968353115349)), (30, np.float64(0.31507145332482367)), (237, np.float64(0.2989169579108771)), (169, np.float64(0.2898613365449613)), (54, np.float64(0.28081058299477923)), (109, np.float64(0.2797860018608304)), (199, np.float64(0.2723606967147888)), (204, np.float64(0.2651565049933823)), (205, np.float64(0.2556672226426009)), (219, np.float64(0.25275214814203995)), (192, np.float64(0.24956717687037827)), (222, np.float64(0.24017659140966927)), (241, np.float64(0.23877863312819783)), (67, np.float64(0.2336202086616476)), (161, np.float64(0.231920840684557)), (69, np.float64(0.2314404618062948)), (116, np.float64(0.22157327242620203)), (32, np.float64(0.21475232187007154)), (7, np.float64(0.2063471207553276)), (211, np.float64(0.20084507191499612)), (95, np.float64(0.18801208531618785)), (139, np.float64(0.18668258079621608)), (110, np.float64(0.1860166217544213)), (213, np.float64(0.1860019451377972)), (209, np.float64(0.18327663010247447)), (148, np.float64(0.1807217047313452)), (194, np.float64(0.18071856893344188)), (5, np.float64(0.17948565714054646)), (33, np.float64(0.17819568963217094)), (46, np.float64(0.17720053212838674)), (229, np.float64(0.1743674977195982)), (228, np.float64(0.162827227006843)), (156, np.float64(0.16186937173834454)), (106, np.float64(0.1501676676351792)), (181, np.float64(0.13743155231884183)), (152, np.float64(0.13639344296824088)), (224, np.float64(0.13601259482195607)), (2, np.float64(0.11679834363153647)), (133, np.float64(0.11541514244441156)), (16, np.float64(0.11474836656199117)), (177, np.float64(0.1106780145552213)), (162, np.float64(0.11038039727199543)), (230, np.float64(0.10820255388532586)), (185, np.float64(0.10581101627873936)), (130, np.float64(0.10347546687986846)), (202, np.float64(0.09848445756008366)), (45, np.float64(0.09767237245013911)), (50, np.float64(0.09594147916699636)), (180, np.float64(0.09344639880789822)), (174, np.float64(0.09152182405435144)), (175, np.float64(0.0885262607165549)), (208, np.float64(0.08512801259311634)), (153, np.float64(0.08404869341298705)), (17, np.float64(0.07548721615410893)), (172, np.float64(0.0683274675487251)), (234, np.float64(0.04838146050571719)), (112, np.float64(0.04600576936094709)), (55, np.float64(0.04149184232792294)), (59, np.float64(0.03963706479424937)), (15, np.float64(0.0375571605369239)), (86, np.float64(0.03689028647378352)), (10, np.float64(0.03575514712386427)), (198, np.float64(0.03454338764498593)), (83, np.float64(0.03444154477161629)), (166, np.float64(0.03442908355358714)), (9, np.float64(0.03423560077137557)), (184, np.float64(0.033826595634503326)), (221, np.float64(0.03366087175948431)), (158, np.float64(0.033278982428571593)), (1, np.float64(0.032316839591326404)), (96, np.float64(0.03198868400464959)), (99, np.float64(0.03194169434867761)), (94, np.float64(0.03076190476447952)), (100, np.float64(0.03053842718158843)), (74, np.float64(0.03012529390239809)), (38, np.float64(0.030099618673366003)), (235, np.float64(0.029981413571801088)), (102, np.float64(0.02981069981370032)), (77, np.float64(0.029071557924765137)), (104, np.float64(0.02898802649365192)), (215, np.float64(0.02897859326553534)), (238, np.float64(0.028888572399830552)), (117, np.float64(0.028078446257974635)), (142, np.float64(0.027859146097082885)), (80, np.float64(0.026702073307710034)), (91, np.float64(0.02664012516348191)), (78, np.float64(0.026621413974021686)), (160, np.float64(0.026538777167915042)), (159, np.float64(0.02653301283895588)), (239, np.float64(0.026475866703190413)), (82, np.float64(0.026305940973147778)), (173, np.float64(0.026282000573176565)), (12, np.float64(0.02585153169055809)), (42, np.float64(0.025815998022966122)), (167, np.float64(0.02551947095672375)), (227, np.float64(0.025261756106398213)), (176, np.float64(0.02524389842764005)), (6, np.float64(0.025216855257594588)), (150, np.float64(0.025049806121484233)), (143, np.float64(0.024909406274945117)), (200, np.float64(0.024820094598422653)), (21, np.float64(0.02475732576175687)), (127, np.float64(0.024725730719572073)), (212, np.float64(0.02462159486266592)), (183, np.float64(0.024548469511792084)), (118, np.float64(0.02447793147862857)), (68, np.float64(0.024371953283177327)), (72, np.float64(0.024298457217857783)), (232, np.float64(0.024220863451803236)), (203, np.float64(0.02414087228018609)), (44, np.float64(0.024081067903237607)), (113, np.float64(0.02372545324472341)), (75, np.float64(0.023695824476444007)), (29, np.float64(0.02340849452129972)), (88, np.float64(0.023301898648954406)), (26, np.float64(0.023235749453363555)), (170, np.float64(0.02322734368214862)), (114, np.float64(0.0232174821953091)), (189, np.float64(0.023185387606304744)), (56, np.float64(0.02299698024916845)), (128, np.float64(0.022787735411520012)), (220, np.float64(0.022736919542344754)), (8, np.float64(0.02258207289254393)), (4, np.float64(0.02254417470302551)), (36, np.float64(0.022525789301416577)), (71, np.float64(0.022350689385973784)), (195, np.float64(0.022332829291244027)), (62, np.float64(0.022293742222403542)), (90, np.float64(0.022084317970236404)), (31, np.float64(0.022084065489438916)), (34, np.float64(0.021921910378544844)), (24, np.float64(0.02181309319065102)), (103, np.float64(0.021660794240207122)), (165, np.float64(0.020688081843809956)), (13, np.float64(0.020587487224188794)), (51, np.float64(0.01823612431485246)), (61, np.float64(0.0169282389212193)), (245, np.float64(0.016662721956261835)), (129, np.float64(0.01664845705886338)), (58, np.float64(0.015334668948639038)), (70, np.float64(0.015119035598627328)), (87, np.float64(0.015111268647031235)), (206, np.float64(0.014938045361401545)), (149, np.float64(0.014565227615946617)), (60, np.float64(0.014453735636628629)), (218, np.float64(0.014414775114903858)), (27, np.float64(0.014316870808770123)), (141, np.float64(0.014173194248628042)), (240, np.float64(0.013873587651309008)), (171, np.float64(0.013856687697967857)), (201, np.float64(0.013596506628622308)), (76, np.float64(0.013471573207274956)), (138, np.float64(0.01317512372472883)), (19, np.float64(0.013147675343585213)), (168, np.float64(0.013074643269776485)), (187, np.float64(0.012973404519891001)), (66, np.float64(0.012947604572397731)), (196, np.float64(0.012840984737592535)), (41, np.float64(0.012476170887264606)), (164, np.float64(0.012466929703387745)), (111, np.float64(0.012399825787050262)), (23, np.float64(0.012342412859949952)), (98, np.float64(0.01234148036259813)), (47, np.float64(0.012192730817604813)), (193, np.float64(0.012044289617745781)), (57, np.float64(0.011876214248861401)), (214, np.float64(0.011844698379490953)), (89, np.float64(0.011842392063797058)), (136, np.float64(0.011745819228247101)), (226, np.float64(0.011697635074966066)), (197, np.float64(0.011684262827546251)), (124, np.float64(0.01159925879698584)), (140, np.float64(0.011563544641869837)), (132, np.float64(0.011477957369035697)), (39, np.float64(0.011416320153134511)), (20, np.float64(0.011410192426912219)), (97, np.float64(0.011393529694160454)), (146, np.float64(0.011392000636892946)), (190, np.float64(0.01138738311909201)), (35, np.float64(0.011379328152374843)), (108, np.float64(0.011321564231331606)), (216, np.float64(0.011281771599367732)), (85, np.float64(0.011265742410660478)), (120, np.float64(0.011258851978990627)), (188, np.float64(0.01125675317107645)), (123, np.float64(0.011254316186664047)), (105, np.float64(0.011185051033694238)), (131, np.float64(0.01115747413913301)), (115, np.float64(0.011154210573226252)), (155, np.float64(0.011127364132432154)), (125, np.float64(0.011111117260302046)), (145, np.float64(0.01104311106565256)), (244, np.float64(0.011033995308463026)), (107, np.float64(0.01098576485852045)), (233, np.float64(0.010973361293857606)), (84, np.float64(0.010945947640201927)), (25, np.float64(0.010944954394936252)), (53, np.float64(0.010855171787596261)), (134, np.float64(0.01084368409088731)), (157, np.float64(0.010821010039238826)), (43, np.float64(0.010718668139914851)), (49, np.float64(0.01067653565445981)), (52, np.float64(0.010620882147466815)), (79, np.float64(0.010613529000711108)), (144, np.float64(0.010590110768801956)), (231, np.float64(0.010495772395737683)), (147, np.float64(0.010493574027615495)), (151, np.float64(0.010446514659345808)), (223, np.float64(0.010433188173294335)), (242, np.float64(0.010401976588285289)), (236, np.float64(0.010366701482646911)), (246, np.float64(0.010325405585356122)), (182, np.float64(0.010242533133323555)), (207, np.float64(0.010156327474266648)), (122, np.float64(0.010148158233868863)), (40, np.float64(0.010144917967892022)), (3, np.float64(0.010109888932570442)), (119, np.float64(0.010072527522078174)), (92, np.float64(0.009896778006507184)), (81, np.float64(0.00989353063290209)), (225, np.float64(0.009768867581640632)), (179, np.float64(0.009730918560726115)), (121, np.float64(0.009608840454731532)), (28, np.float64(0.009595561834364781)), (210, np.float64(0.009474248227532013)), (137, np.float64(0.009428893601175268)), (48, np.float64(0.009190787509300451)), (126, np.float64(0.003522289704220864)), (22, np.float64(0.0)), (101, np.float64(0.0)), (163, np.float64(0.0)), (178, np.float64(0.0)), (191, np.float64(0.0))]
[(64, np.float64(0.45311114162955807)), (217, np.float64(0.4200539456275653)), (93, np.float64(0.416805651127417)), (154, np.float64(0.39911681617817335)), (0, np.float64(0.38896543251188437)), (73, np.float64(0.38838855199503136)), (63, np.float64(0.3768794014077303)), (18, np.float64(0.3575160490039907)), (186, np.float64(0.35342137210419367)), (243, np.float64(0.348593386634705)), (14, np.float64(0.3452581845696204)), (135, np.float64(0.3277061555077906)), (65, np.float64(0.3251042839624321)), (37, np.float64(0.3203968353115349)), (30, np.float64(0.31507145332482367)), (237, np.float64(0.2989169579108771)), (169, np.float64(0.2898613365449613)), (54, np.float64(0.28081058299477923)), (109, np.float64(0.2797860018608304)), (199, np.float64(0.2723606967147888)), (204, np.float64(0.2651565049933823)), (205, np.float64(0.2556672226426009)), (219, np.float64(0.25275214814203995)), (192, np.float64(0.24956717687037827)), (222, np.float64(0.24017659140966927)), (241, np.float64(0.23877863312819783)), (67, np.float64(0.2336202086616476)), (161, np.float64(0.231920840684557)), (69, np.float64(0.2314404618062948)), (116, np.float64(0.22157327242620203)), (32, np.float64(0.21475232187007154)), (7, np.float64(0.2063471207553276)), (211, np.float64(0.20084507191499612)), (95, np.float64(0.18801208531618785)), (139, np.float64(0.18668258079621608)), (110, np.float64(0.1860166217544213)), (213, np.float64(0.1860019451377972)), (209, np.float64(0.18327663010247447)), (148, np.float64(0.1807217047313452)), (194, np.float64(0.18071856893344188)), (5, np.float64(0.17948565714054646)), (33, np.float64(0.17819568963217094)), (46, np.float64(0.17720053212838674)), (229, np.float64(0.1743674977195982)), (228, np.float64(0.162827227006843)), (156, np.float64(0.16186937173834454)), (106, np.float64(0.1501676676351792)), (181, np.float64(0.13743155231884183)), (152, np.float64(0.13639344296824088)), (224, np.float64(0.13601259482195607)), (2, np.float64(0.11679834363153647)), (133, np.float64(0.11541514244441156)), (16, np.float64(0.11474836656199117)), (177, np.float64(0.1106780145552213)), (162, np.float64(0.11038039727199543)), (230, np.float64(0.10820255388532586)), (185, np.float64(0.10581101627873936)), (130, np.float64(0.10347546687986846)), (202, np.float64(0.09848445756008366)), (45, np.float64(0.09767237245013911)), (50, np.float64(0.09594147916699636)), (180, np.float64(0.09344639880789822)), (174, np.float64(0.09152182405435144)), (175, np.float64(0.0885262607165549)), (208, np.float64(0.08512801259311634)), (153, np.float64(0.08404869341298705)), (17, np.float64(0.07548721615410893)), (172, np.float64(0.0683274675487251)), (234, np.float64(0.04838146050571719)), (112, np.float64(0.04600576936094709)), (55, np.float64(0.04149184232792294)), (59, np.float64(0.03963706479424937)), (15, np.float64(0.0375571605369239)), (86, np.float64(0.03689028647378352)), (10, np.float64(0.03575514712386427)), (198, np.float64(0.03454338764498593)), (83, np.float64(0.03444154477161629)), (166, np.float64(0.03442908355358714)), (9, np.float64(0.03423560077137557)), (184, np.float64(0.033826595634503326)), (221, np.float64(0.03366087175948431)), (158, np.float64(0.033278982428571593)), (1, np.float64(0.032316839591326404)), (96, np.float64(0.03198868400464959)), (99, np.float64(0.03194169434867761)), (94, np.float64(0.03076190476447952)), (100, np.float64(0.03053842718158843)), (74, np.float64(0.03012529390239809)), (38, np.float64(0.030099618673366003)), (235, np.float64(0.029981413571801088)), (102, np.float64(0.02981069981370032)), (77, np.float64(0.029071557924765137)), (104, np.float64(0.02898802649365192)), (215, np.float64(0.02897859326553534)), (238, np.float64(0.028888572399830552)), (117, np.float64(0.028078446257974635)), (142, np.float64(0.027859146097082885)), (80, np.float64(0.026702073307710034)), (91, np.float64(0.02664012516348191)), (78, np.float64(0.026621413974021686)), (160, np.float64(0.026538777167915042)), (159, np.float64(0.02653301283895588)), (239, np.float64(0.026475866703190413)), (82, np.float64(0.026305940973147778)), (173, np.float64(0.026282000573176565)), (12, np.float64(0.02585153169055809)), (42, np.float64(0.025815998022966122)), (167, np.float64(0.02551947095672375)), (227, np.float64(0.025261756106398213)), (176, np.float64(0.02524389842764005)), (6, np.float64(0.025216855257594588)), (150, np.float64(0.025049806121484233)), (143, np.float64(0.024909406274945117)), (200, np.float64(0.024820094598422653)), (21, np.float64(0.02475732576175687)), (127, np.float64(0.024725730719572073)), (212, np.float64(0.02462159486266592)), (183, np.float64(0.024548469511792084)), (118, np.float64(0.02447793147862857)), (68, np.float64(0.024371953283177327)), (72, np.float64(0.024298457217857783)), (232, np.float64(0.024220863451803236)), (203, np.float64(0.02414087228018609)), (44, np.float64(0.024081067903237607)), (113, np.float64(0.02372545324472341)), (75, np.float64(0.023695824476444007)), (29, np.float64(0.02340849452129972)), (88, np.float64(0.023301898648954406)), (26, np.float64(0.023235749453363555)), (170, np.float64(0.02322734368214862)), (114, np.float64(0.0232174821953091)), (189, np.float64(0.023185387606304744)), (56, np.float64(0.02299698024916845)), (128, np.float64(0.022787735411520012)), (220, np.float64(0.022736919542344754)), (8, np.float64(0.02258207289254393)), (4, np.float64(0.02254417470302551)), (36, np.float64(0.022525789301416577)), (71, np.float64(0.022350689385973784)), (195, np.float64(0.022332829291244027)), (62, np.float64(0.022293742222403542)), (90, np.float64(0.022084317970236404)), (31, np.float64(0.022084065489438916)), (34, np.float64(0.021921910378544844)), (24, np.float64(0.02181309319065102)), (103, np.float64(0.021660794240207122)), (165, np.float64(0.020688081843809956)), (13, np.float64(0.020587487224188794)), (51, np.float64(0.01823612431485246)), (61, np.float64(0.0169282389212193)), (245, np.float64(0.016662721956261835)), (129, np.float64(0.01664845705886338)), (58, np.float64(0.015334668948639038)), (70, np.float64(0.015119035598627328)), (87, np.float64(0.015111268647031235)), (206, np.float64(0.014938045361401545)), (149, np.float64(0.014565227615946617)), (60, np.float64(0.014453735636628629)), (218, np.float64(0.014414775114903858)), (27, np.float64(0.014316870808770123)), (141, np.float64(0.014173194248628042)), (240, np.float64(0.013873587651309008)), (171, np.float64(0.013856687697967857)), (201, np.float64(0.013596506628622308)), (76, np.float64(0.013471573207274956)), (138, np.float64(0.01317512372472883)), (19, np.float64(0.013147675343585213)), (168, np.float64(0.013074643269776485)), (187, np.float64(0.012973404519891001)), (66, np.float64(0.012947604572397731)), (196, np.float64(0.012840984737592535)), (41, np.float64(0.012476170887264606)), (164, np.float64(0.012466929703387745)), (111, np.float64(0.012399825787050262)), (23, np.float64(0.012342412859949952)), (98, np.float64(0.01234148036259813)), (47, np.float64(0.012192730817604813)), (193, np.float64(0.012044289617745781)), (57, np.float64(0.011876214248861401)), (214, np.float64(0.011844698379490953)), (89, np.float64(0.011842392063797058)), (136, np.float64(0.011745819228247101)), (226, np.float64(0.011697635074966066)), (197, np.float64(0.011684262827546251)), (124, np.float64(0.01159925879698584)), (140, np.float64(0.011563544641869837)), (132, np.float64(0.011477957369035697)), (39, np.float64(0.011416320153134511)), (20, np.float64(0.011410192426912219)), (97, np.float64(0.011393529694160454)), (146, np.float64(0.011392000636892946)), (190, np.float64(0.01138738311909201)), (35, np.float64(0.011379328152374843)), (108, np.float64(0.011321564231331606)), (216, np.float64(0.011281771599367732)), (85, np.float64(0.011265742410660478)), (120, np.float64(0.011258851978990627)), (188, np.float64(0.01125675317107645)), (123, np.float64(0.011254316186664047)), (105, np.float64(0.011185051033694238)), (131, np.float64(0.01115747413913301)), (115, np.float64(0.011154210573226252)), (155, np.float64(0.011127364132432154)), (125, np.float64(0.011111117260302046)), (145, np.float64(0.01104311106565256)), (244, np.float64(0.011033995308463026)), (107, np.float64(0.01098576485852045)), (233, np.float64(0.010973361293857606)), (84, np.float64(0.010945947640201927)), (25, np.float64(0.010944954394936252)), (53, np.float64(0.010855171787596261)), (134, np.float64(0.01084368409088731)), (157, np.float64(0.010821010039238826)), (43, np.float64(0.010718668139914851)), (49, np.float64(0.01067653565445981)), (52, np.float64(0.010620882147466815)), (79, np.float64(0.010613529000711108)), (144, np.float64(0.010590110768801956)), (231, np.float64(0.010495772395737683)), (147, np.float64(0.010493574027615495)), (151, np.float64(0.010446514659345808)), (223, np.float64(0.010433188173294335)), (242, np.float64(0.010401976588285289)), (236, np.float64(0.010366701482646911)), (246, np.float64(0.010325405585356122)), (182, np.float64(0.010242533133323555)), (207, np.float64(0.010156327474266648)), (122, np.float64(0.010148158233868863)), (40, np.float64(0.010144917967892022)), (3, np.float64(0.010109888932570442)), (119, np.float64(0.010072527522078174)), (92, np.float64(0.009896778006507184)), (81, np.float64(0.00989353063290209)), (225, np.float64(0.009768867581640632)), (179, np.float64(0.009730918560726115)), (121, np.float64(0.009608840454731532)), (28, np.float64(0.009595561834364781)), (210, np.float64(0.009474248227532013)), (137, np.float64(0.009428893601175268)), (48, np.float64(0.009190787509300451)), (126, np.float64(0.003522289704220864)), (22, np.float64(0.0)), (101, np.float64(0.0)), (163, np.float64(0.0)), (178, np.float64(0.0)), (191, np.float64(0.0))]
           PropertyName  SimilarityScore
64      Ace Palm Floors               64
217         Yashika 104              217
93       JMS The Nation               93
154       India Rashtra              154
0    Smartworld One DXP                0